CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Models/Locations/LocationFlag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TentsNTrails.Models
{
    public enum  Flag {
        [Display(Name = "Have Been")]
        HaveBeen,
        [Display(Name = "Want to Go")]
        WantToGo,
        [Display(Name = "Want to Go Again")]
        GoAgain
    }

    public class LocationFlag
    {
        [Key]
        public int FlagID { get; set; }
        //public int UserID { get; set; }
        public int LocationID { get; set; }
        public Flag Flag { get; set; }

        public virtual User User { get; set; }
        public virtual Location Location { get; set; }
    }
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Models/Locations/LocationFlagViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TentsNTrails.Models
{
    public class LocationFlagViewModel
    {
        public virtual ICollection<LocationFlag> BeenThereLocations { get; set; }
        public virtual ICollection<LocationFlag> WantToGoLocations { get; set; }
        public virtual ICollection<LocationFlag> GoAgainLocations { get; set; }
        public bool HasSavedLocations { get; set; }
    }
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TentsNTrails.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;
using System.Web.Routing;
using TentsNTrails.Controllers;
using System.Xml.Linq;
using System.Text;


namespace TentsNTrails.Controllers
{
    public class LocationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<User> manager;
            
        public LocationController () 
        {
            manager = new UserManager<User>(new UserStore<User>(db));
        }

        // ************************************************************************************************************
        // INDEX
        // ************************************************************************************************************

        /// <summary>
        /// GET: Location
        /// </summary>
        /// <returns>The Location/Index view.</returns> 
        public ActionResult Index(int? recreationID, string sortOrder, string currentFilter)
        {
            // *************************************************
            // sorting by rating functionality
            // *************************************************

            // ViewModel
            LocationIndexViewModel viewModel = new LocationIndexViewModel();

            var defaultRec = Enumerable.Repeat(new SelectListItem
            {
                Value = "-1",
                Text = "Recreation Type"
            }, count: 1);

            var recList = new SelectList(db.Recreations, "RecreationID", "Label");
            viewModel.Recreations = defaultRec.Concat(recList);

            // *************************************************
            // filter by Recreation
            // *************************************************            
            if (recreationID.HasValue)
            {
                viewModel.Locations = db.LocationRecreations
                    .Where(lr => lr.RecreationID == recreationID)
                    .Select(lr => lr.Location).ToList();
            }
            else
            {
                viewModel.Locations = db.Locations
                    .Include(l => l.Recreations)
                    .ToList();
            }

            // *************************************************
            // sort by name, rating, and difficulty
            // *************************************************
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.RatingSortParm = sortOrder == "Rating" ? "rating_desc" : "Rating";
            ViewBag.DifficultySortParm = sortOrder == "difficulty_desc" ? "Difficulty" : "difficulty_desc";

            // *************************************************
            // LOCATION LISTS
            // *************************************************
            viewModel.TopRatedLocations = GetTopRatedLocations(5);
            viewModel.MostRecentLocations = GetMostRecentLocations(5);
            if (User.Identity.IsAuthenticated)
            {
                viewModel.PersonalRecommendations = GetPersonalRecommendations(5);
                viewModel.FriendRecommendations = GetFriendRecommendations(5);
            }
            // *************************************************
            // calculate center of map display
            // *************************************************    
            Location center = Location.GetLatLongCenter(viewModel.Locations);
            System.Diagnostics.Debug.WriteLine("centerLatitude:  " + center.Latitude);
            System.Diagnostics.Debug.WriteLine("centerLongitude: " + center.Longitude);
            ViewBag.centerLatitude = center.Latitude;
            ViewBag.centerLongitude = center.Longitude;

            return View(viewModel);
        }


        // ************************************************************************************************************
        // HELPER METHODS
        // ************************************************************************************************************

        /// <summary>
        /// Helper method to format a collection of strings into a human-readable string,
        /// in an array-literal format (i.e. '{"hello", "world"}'.
        /// </summary>
        /// <param name="strings">The collection of strings to format.</param>
        /// <returns>A formatted string.</returns>
        public string GetArrayFormattedString(ICollection<string> strings)
        {
            // case 1 - null
            if (strings == null) return "null";

            int length = strings.Count();

            // case 2 - empty
            if (length == 0) return "{ }";

            // case 3 - general
            string[] array = strings.ToArray();
            StringBuilder sb = new StringBuilder();
            sb.Append('{');
            for (int i = 0; i < length; i++)
            {
                sb.Append(String.Format("\"{0}\"{1}", array[i], i + 1 < length ? ", " : ""));
            }
            sb.Append('}');
            return sb.ToString();
        }


        /// <summary>
        /// Get the specified amount of Top-Rated Locations.
        /// </summary>
        /// <param name="amount">The amount to get.</param>
        /// <returns>A list of Locations.</returns>
        public List<Location> GetTopRatedLocations(int amount)
        {
            // Divide the total number of ratings by the number of locations to get
            // We decided that the top rated locations have to have at least half as many votes as average
            int LocationCount = db.Locations.Count();
            int avgRatingsPerLocation = -1;

            if (LocationCount != 0)avgRatingsPerLocation = db.Reviews.Count() / LocationCount;
            else avgRatingsPerLocation = 1;
            
            int minRatings = (int)(.5 * avgRatingsPerLocation);
            var locations =  db.Locations.Where(l => l.Reviews.Count() > minRatings);
            return SortByRatingAndTake(locations, amount);

            /*
            int minRatings = (int)(.5 * avgRatingsPerLocation);
            return db.Locations
                .Where(l => l.Reviews.Count() > minRatings)
                .OrderByDescending(l => 
                    l.Reviews.Where(r => r.Rating).Count()
                    /l.Reviews.Count()
                ).Take(amount).ToList();
             */
        }

        /// <summary>
        /// Get the specified amount of most recently added Locations.
        /// </summary>
        /// <param name="amount">The amount to get.</param>
        /// <returns>A list of Locations.</returns>
        public List<Location> GetMostRecentLocations(int amount)
        {
            return db.Locations
                .OrderByDescending(l => l.DateCreated)
                .ThenByDescending(l =>
                    l.Reviews.Where(r => r.Rating).Count()
                    / ( (double) (l.Reviews.Count() == 0 ? 1 : l.Reviews.Count()) )
                )
                .Take(amount).ToList();
        }

        /// <summary>
        /// Get a list of locations that are recommended by the website based on your personal interests.
        /// </summary>
        /// <returns>A list of Locations.</returns>
        public List<Location> GetPersonalRecommendations(int amount)
        {
            System.Diagnostics.Debug.WriteLine(String.Format("GetPersonalRecommendations({0})", amount));
            // ensure user is logged in.
            if (!User.Identity.IsAuthenticated)
            {
                return new List<Location>();
            }

            User user = db.Users.Find(User.Identity.GetUserId());

            // get all Recreations the user partakes in.
            IQueryable<Recreation> userActivities = db.UserRecreations
                .Where(ur => ur.User.Equals(user.Id))
                .Select(r => r.Recreation);
             
            // get all positively reviewed Locations by the user
            IQueryable<Review> reviews = db.Reviews.Where(r =>
                    r.User.Id.Equals(user.Id)
                );

            // get all matching bookmarked Locations by the user
            IQueryable<Location> bookmarkedLocations = db.LocationFlags.Where(f =>
                    f.User.Id.Equals(user.Id)
                    && (f.Flag == Flag.HaveBeen
                    || f.Flag == Flag.WantToGo)
                ).Select(f => f.Location);

            // union the locations.
            IQueryable<Location> locations = null;

            System.Diagnostics.Debug.WriteLine(String.Format("{0} bookmarks, {1} reviews, {2} recreations", bookmarkedLocations.Count(), reviews.Count(), userActivities.Count()));

            // union the bookmarkedLocations and the reviewed locations.
            locations = bookmarkedLocations.Union(reviews.Select(r => r.Location));

            // get the states of those locations
            IQueryable<string> states = locations.Select(u => u.StateID);

            // finally, get ALL locations that contain one of the user's rec types, UNIONED with locations are IN the states of the result that are NOT in result, AND are NOT reviewed by the user.
            IQueryable<Location> result;

            result = userActivities
                .SelectMany(r => r.RecOptions)
                .Select(lr => lr.Location)
                .Union(db.Locations.Where(l =>
                    states.Contains(l.StateID)
                    && !locations.Contains(l)
                )
            ).Where(l => 
                !reviews.Select(r => r.Location)
                .Contains(l)
            );          

            return SortByRatingAndTake(result, amount);
        }

        /// <summary>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Controllers/LocationFlagController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using TentsNTrails.Models;

namespace TentsNTrails.Controllers
{
    public class LocationFlagController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<User> manager;
            
        public LocationFlagController () 
        {
            manager = new UserManager<User>(new UserStore<User>(db));
        }

        // GET: LocationFlag
        [Authorize]
        public ActionResult Index()
        {
            User currentUser = manager.FindById(User.Identity.GetUserId());
            
            var locationFlags = db.LocationFlags.Include(l => l.Location).
                Where(l => l.User.Id == currentUser.Id).ToList();

            LocationFlagViewModel viewModel = new LocationFlagViewModel();

            if (locationFlags.Count() == 0)
            {
                // they haven't saved any locations
                viewModel.HasSavedLocations = false;
                viewModel.BeenThereLocations = new List<LocationFlag>();
                viewModel.WantToGoLocations = new List<LocationFlag>();
                viewModel.GoAgainLocations = new List<LocationFlag>();
            }
            else
            {
                // Fill the three lists with their respective LocationFlags
                viewModel.BeenThereLocations = locationFlags.Where(l => l.Flag == Flag.HaveBeen).ToList();
                viewModel.WantToGoLocations = locationFlags.Where(l => l.Flag == Flag.WantToGo).ToList();
                viewModel.GoAgainLocations = locationFlags.Where(l => l.Flag == Flag.GoAgain).ToList();
                viewModel.HasSavedLocations = true;
                ViewBag.centerLatitude = 39.8282;
                ViewBag.centerLongitude = -98.5795;
            }

            return View(viewModel);
        }

        // GET: LocationFlag/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label");
            return View();
        }

        // POST: LocationFlag/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "FlagID,LocationID,Flag")] LocationFlag locationFlag)
        {
            if (ModelState.IsValid)
            {
                db.LocationFlags.Add(locationFlag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label", locationFlag.LocationID);
            return View(locationFlag);
        }

        // GET: LocationFlag/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LocationFlag locationFlag = db.LocationFlags.Find(id);
            if (locationFlag == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label", locationFlag.LocationID);
            return View(locationFlag);
        }

        // POST: LocationFlag/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "FlagID,LocationID,Flag")] LocationFlag locationFlag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(locationFlag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label", locationFlag.LocationID);
            return View(locationFlag);
        }

        // GET: LocationFlag/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LocationFlag locationFlag = db.LocationFlags.Find(id);
            if (locationFlag == null)
            {
                return HttpNotFound();
            }
            return View(locationFlag);
        }

        // POST: LocationFlag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            LocationFlag locationFlag = db.LocationFlags.Find(id);
            db.LocationFlags.Remove(locationFlag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/LocationFlag/Create.cshtml
@model TentsNTrails.Models.LocationFlag

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LocationFlag</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, "LocationID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Flag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Flag, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Flag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/LocationFlag/Delete.cshtml
@model TentsNTrails.Models.LocationFlag

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LocationFlag</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location.Label)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.Label)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flag)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/LocationFlag/Details.cshtml
@model TentsNTrails.Models.LocationFlag

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>LocationFlag</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location.Label)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.Label)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flag)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FlagID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/LocationFlag/Edit.cshtml
@model TentsNTrails.Models.LocationFlag

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LocationFlag</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FlagID)

        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, "LocationID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Flag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Flag, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Flag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/LocationFlag/Index.cshtml
@model TentsNTrails.Models.LocationFlagViewModel
@using TentsNTrails.Models;

<!-- MAPS API -->
<script src="http://maps.googleapis.com/maps/api/js"></script>
<script src="~/Scripts/google-map-setup.js"></script>
<script>
    var addMarkers = function(map, markers) {
        @foreach (var item in Model.BeenThereLocations)
        {
            @:console.log("latitude:" + @item.Location.Latitude + " longitude: " +  @item.Location.Longitude);
            @:var marker = new google.maps.Marker({position: new google.maps.LatLng(@item.Location.Latitude, @item.Location.Longitude), map: map, icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'});
            @:var infowindow = new google.maps.InfoWindow({content: 'Loading...'});
            @:marker.html='<div><img id="location-image-preview" src="@Url.Content(item.Location.PreviewImageURL)" title="Preview Image" alt="Image of @item.Location.Label" style="width: 100px; height: auto; margin:0 auto;" /><br /><div class="label" text-align="center">@Html.ActionLink(item.Location.Label, "Details", "Location", new { id = item.Location.LocationID }, null)</div></div>';
            @:google.maps.event.addListener(marker, 'click', function() {infowindow.setContent(this.html); infowindow.open(map,this);});
            @:markers.push(marker);
        }
        @foreach (var item in Model.WantToGoLocations)
        {
            @:console.log("latitude:" + @item.Location.Latitude + " longitude: " +  @item.Location.Longitude);
            @:var marker = new google.maps.Marker({position: new google.maps.LatLng(@item.Location.Latitude, @item.Location.Longitude), map: map, icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'});
            @:var infowindow = new google.maps.InfoWindow({content: 'Loading...'});
            @:marker.html='<div><img id="location-image-preview" src="@Url.Content(item.Location.PreviewImageURL)" title="Preview Image" alt="Image of @item.Location.Label" style="width: 100px; height: auto; margin:0 auto;" /><br /><div class="label" text-align="center">@Html.ActionLink(item.Location.Label, "Details", "Location", new { id = item.Location.LocationID }, null)</div></div>';
            @:google.maps.event.addListener(marker, 'click', function() {infowindow.setContent(this.html); infowindow.open(map,this);});
            @:markers.push(marker);
        }
        @foreach (var item in Model.GoAgainLocations)
        {
            
            @:console.log("latitude:" + @item.Location.Latitude + " longitude: " +  @item.Location.Longitude);
            @:var marker = new google.maps.Marker({position: new google.maps.LatLng(@item.Location.Latitude, @item.Location.Longitude), map: map, icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'});
            @:var infowindow = new google.maps.InfoWindow({content: 'Loading...'});
            @:marker.html='<div><img id="location-image-preview" src="@Url.Content(item.Location.PreviewImageURL)" title="Preview Image" alt="Image of @item.Location.Label" style="width: 100px; height: auto; margin:0 auto;" /><br /><div class="label" text-align="center">@Html.ActionLink(item.Location.Label, "Details", "Location", new { id = item.Location.LocationID }, null)</div></div>';
            @:google.maps.event.addListener(marker, 'click', function() {infowindow.setContent(this.html); infowindow.open(map,this);});
            @:markers.push(marker);
        }
    };
    var centerLat = @Location.CENTER.Latitude;
    var centerLng = @Location.CENTER.Longitude;
    var minZoom = 6;
    var ourMap = new TntMap(centerLat,centerLng, addMarkers, minZoom);
    ourMap.create();
</script>

@{
    ViewBag.Title = "My Bookmarked Locations";
}

<!-- FORMATTING -->
<script type="text/javascript" src="~/Scripts/jquery-1.10.2.js"></script>

<h2>@ViewBag.Title</h2>

@if (Model.HasSavedLocations)
{ 
    <!-- MAP OF BOOKMARKED LOCATIONS-->
    <div id="googleMap" style="width:80%;height:300px;"></div>
    <p></p>


    <table class="table centered">
        <tr>
            <th>
                Been There <img src="http://maps.google.com/mapfiles/ms/icons/blue-dot.png" alt="Blue Pin" style="height:70%" />
            </th>
            <th>
                Want to Go <img src="http://maps.google.com/mapfiles/ms/icons/red-dot.png" alt="Red Pin" style="height:70%" />
            </th>
            <th>
                Want to Go Again <img src="http://maps.google.com/mapfiles/ms/icons/green-dot.png" alt="Green Pin" style="height:70%"/>
            </th>
        </tr>
        
        <tr>
            <td>
                @foreach (var item in Model.BeenThereLocations)
                {
                    @Html.ActionLink(item.Location.Label, "Details", "Location", new { id = item.Location.LocationID }, null)
                    <br/>
                }
            </td>
            <td>
                @foreach (var item in Model.WantToGoLocations)
                {
                    @Html.ActionLink(item.Location.Label, "Details", "Location", new { id = item.Location.LocationID }, null)
                    <br />
                }
            </td>
            <td>
                @foreach (var item in Model.GoAgainLocations)
                {
                    @Html.ActionLink(item.Location.Label, "Details", "Location", new { id = item.Location.LocationID }, null)
                    <br />
                }
            </td>
        </tr>
    </table>
}
else
{
    <p>
        Looks like you haven't bookmarked any locations yet. Save a  
        <u>@Html.ActionLink("location", "Index", "Location")</u>
        that you've <b>been to</b> or <b>want to go to</b>. (When you're in the Details page for a location, there are links above the map.)
    </p>
}