CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Models/Events/EventParticipants.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TentsNTrails.Models
{
    public class EventParticipants
    {
        [Key]
        public int EventParticipationID { get; set; }

        public virtual Events Event { get; set; }

        public virtual User Participant { get; set; }
    }
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Controllers/EventsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TentsNTrails.Models;
using TentsNTrails.Controllers;

namespace TentsNTrails.Controllers
{
    
    public class EventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<User> manager;

        public EventsController()
        {
            db = new ApplicationDbContext();
            manager = new UserManager<User>(new UserStore<User>(db));
        }

        // GET: Events
        public ActionResult Index()
        {
            var events = db.Events.Include(e => e.Location).OrderBy(e => e.Date);
            ViewBag.centerLatitude = 39.8282;
            ViewBag.centerLongitude = -98.5795;
            return View(events.ToList());
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Events events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            
            if (User.Identity.GetUserId() != null)
                if (events.Participants.Where(e => e.Participant.Id.Equals(manager.FindById(User.Identity.GetUserId()).Id)).Count() == 0)
                {
                    ViewBag.Join = true;
                }
                else
                {
                    ViewBag.Join = false;
                }
            else
            {
                ViewBag.Join = true;
            }

            var commentList = db.EventComments.Where(e => e.EventID == id).ToList();
            if (commentList.Count == 0)
            {
                ViewBag.HasComments = false;
            }
            else
            {
                ViewBag.HasComments = true;
            }

            return View(events);
        }

        [Authorize]
        // GET: Events/Create
        public ActionResult Create()
        {
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventID,Name,Description,Date,LocationID")] Events events)
        {
            if (events.Date < DateTime.Now)
            {
                ModelState.AddModelError("Date", "The date must be in the future.");
            }

            if (ModelState.IsValid)
            {
                events.Organizer = manager.FindById(User.Identity.GetUserId());

                db.Events.Add(events);
                db.SaveChanges();

                EventParticipants ep = new EventParticipants();
                ep.EventParticipationID = events.EventID;
                ep.Event = db.Events.Where(e => e.EventID == events.EventID).ToList().First();
                ep.Participant = events.Organizer;
                db.EventParticipants.Add(ep);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label", events.LocationID);
            return View(events);
        }

        [Authorize]
        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Events events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label", events.LocationID);
            return View(events);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventID,Name,Description,Date,LocationID")] Events events)
        {
            if (ModelState.IsValid)
            {
                db.Entry(events).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label", events.LocationID);
            return View(events);
        }

        // GET: Events/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Events events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            return View(events);
        }

        // POST: Events/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Events events = db.Events.Find(id);
            db.Events.Remove(events);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public PartialViewResult Summary(int? id, int? imageSize, string redirectAction, string redirectController)
        {
            // find location
            Events events = db.Events
                .Include(l => l.Location)
                .Where(l => l.EventID == id)
                .SingleOrDefault();

            // error checking for null case
            if (events == null) return PartialView(events);

            ViewBag.Size = imageSize ?? 100;
            ViewBag.redirectAction = redirectAction ?? "Index";
            ViewBag.redirectController = redirectController ?? "Location";
            //System.Diagnostics.Debug.WriteLine(String.Format("LocationController.Summary(LocationID: {0}) ViewBag.redirectAction:     {1}", id ?? -1, redirectAction ?? "Index"));
            //System.Diagnostics.Debug.WriteLine(String.Format("LocationController.Summary(LocationID: {0}) ViewBag.redirectController: {1}", id ?? -1, redirectController ?? "Location"));
            // done
            return PartialView(events);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TentsNTrails.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;
using TentsNTrails.Azure;
using PagedList;


namespace TentsNTrails.Controllers
{
    public class ProfileController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<User> manager;
        private PhotoService photoService = new PhotoService();
            
        public ProfileController () 
        {
            manager = new UserManager<User>(new UserStore<User>(db));
        }

        // GET: Profile
        public ActionResult Index(String username, ProfileMessageId? message)
        {
            System.Diagnostics.Trace.WriteLine("Profile.Index");
            System.Diagnostics.Debug.WriteLine("Profile.Index");
            User profileUser = manager.FindById(User.Identity.GetUserId());
            ViewBag.IsConnected = false;
            ViewBag.HasConnectionRequest = false;
            ViewBag.HasSentRequest = false;
            ViewBag.HasRequests = false;

            if (username != null && !username.Equals(profileUser.UserName)) //Traveling to another user's profile
            {
                profileUser = db.Users.Where(user => user.UserName == username).First();
                ViewBag.IsPrivate = profileUser.Private; //Tells the view what to display based on user settings
                ViewBag.IsOnOwnProfile = false;

                // Check if the two users are already connected some way (if this is a logged in user)
                User currentUser = manager.FindById(User.Identity.GetUserId());
                if (currentUser != null)
                {
                    // Check for connection
                    var connection = db.Connections.Where(c => (c.User1.UserName == currentUser.UserName && c.User2.UserName == profileUser.UserName) ||
                        (c.User2.UserName == currentUser.UserName && c.User1.UserName == profileUser.UserName));
                    if (connection.Count() > 0)
                    {
                        ViewBag.IsConnected = true;
                    }

                    // Check if the person whose profile we're looking at has sent a ConnectionRequest
                    var requestTo = db.ConnectionRequests.Where(c => (c.RequestedUser.UserName == currentUser.UserName && c.Sender.UserName == profileUser.UserName));
                    if (requestTo.Count() > 0)
                    {
                        ViewBag.HasConnectionRequest = true;
                    }
                    else
                    {
                        var requestFrom = db.ConnectionRequests.Where(c => (c.Sender.UserName == currentUser.UserName && c.RequestedUser.UserName == profileUser.UserName));
                        if (requestFrom.Count() > 0)
                        {
                            ViewBag.HasSentRequest = true;
                        }
                    }
                }
            }
            else //Traveling to personal profile page
            {
                ViewBag.IsOnOwnProfile = true;
                ViewBag.IsPrivate = false;  //A user would never be private to them self.

                var requests = db.ConnectionRequests.Where(u => u.RequestedUser.UserName == profileUser.UserName);
                if(requests.Count() > 0)
                {
                    ViewBag.HasRequests = true;
                }
            }

            //add user rankings
            var allUsers = db.Users.ToList();
                // sort the users by their contributions, but only count it if they have at least 1 contribution
            var topUsers = allUsers
                .Where(u => u.TotalContributions() > 0)
                .OrderByDescending(e => e.TotalContributions())
                .ToList();

            ViewBag.LeaderboardOverall = "Not Ranked";
            for (int i = 0; i < topUsers.Count; i++)
            {
                if (topUsers.ElementAt(i).Id == profileUser.Id)
                {
                    ViewBag.LeaderboardOverall = i + 1;
                }
            }

            var topReviewers = allUsers
                .Where(u => u.TotalReviews() > 0)
                .OrderByDescending(e => e.TotalReviews())
                .ToList();

            ViewBag.LeaderboardReview = "Not Ranked";
            for (int i = 0; i < topReviewers.Count; i++)
            {
                if (topReviewers.ElementAt(i).Id == profileUser.Id)
                {
                    ViewBag.LeaderboardReview = i + 1;
                }
            }

            var topMediaUploaders = allUsers
                .Where(u => u.TotalMediaItems() > 0)
                .OrderByDescending(e => e.TotalMediaItems())
                .ToList();

            ViewBag.onLeaderboardMedia = "Not Ranked";
            for (int i = 0; i < topMediaUploaders.Count; i++)
            {
                if (topMediaUploaders.ElementAt(i).Id == profileUser.Id)
                {
                    ViewBag.onLeaderboardMedia = i + 1;
                }
            }

            //add user activities
            List<UserRecreation> ur = db.UserRecreations.Where(u => u.User == profileUser.Id).ToList();
            profileUser.UserActivities = ur;

            //add user reviews
            List<Review> uRV = db.Reviews.Where(r => r.User.Id == profileUser.Id).ToList().OrderByDescending(t => t.ReviewDate).Take(5).ToList();
            //uRV.OrderByDescending(t => t.ReviewDate).Take(5).ToList();
            profileUser.UserReviews = uRV;

            //add user bookmarks
            List<LocationFlag> locationFlags = db.LocationFlags.Include(l => l.Location).Where(f => f.User.Id == profileUser.Id).ToList();
            if (locationFlags.Count > 0)
            {
                ViewBag.HasSavedLocations = true;
                // Fill the three lists with their respective LocationFlags
                profileUser.BeenThereLocations = locationFlags.Where(l => l.Flag == Flag.HaveBeen).ToList();
                profileUser.WantToGoLocations = locationFlags.Where(l => l.Flag == Flag.WantToGo).ToList();
                profileUser.GoAgainLocations = locationFlags.Where(l => l.Flag == Flag.GoAgain).ToList();
                ViewBag.centerLatitude = 39.8282;
                ViewBag.centerLongitude = -98.5795;
            }
            else
            {
                ViewBag.HasSavedLocations = false;
            }

            //add user's location images
            List<LocationImage> images = db.LocationImages.Where(i => i.User.Id == profileUser.Id).ToList();
            List<LocationImage> smallImage = new List<LocationImage>();
            int count = 0;
            while (smallImage.Count < 5 && count < images.Count)
            {
                smallImage.Add(images.ElementAt(count));
                count++;
            }
            ViewBag.ImagesCount = images.Count();
            profileUser.UserLocationImages = smallImage;

            //add user's location videos
            List<Video> videos = db.Videos.Where(i => i.User.Id == profileUser.Id).ToList();
            List<Video> smallVideo = new List<Video>();
            int countVid = 0;
            while (smallVideo.Count < 4 && countVid < videos.Count)
            {
                smallVideo.Add(videos.ElementAt(countVid));
                countVid++;
            }
            ViewBag.VideosCount = videos.Count();
            profileUser.UserLocationVideos = smallVideo;


            ViewBag.SuccessMessage =
                message == ProfileMessageId.ConnectionSuccess ? "Congratulations! You are now connected to " + profileUser.UserName + "."
                : message == ProfileMessageId.RequestSuccess ? "Congratulations! You have sent a connection request to " + profileUser.UserName + "."
                : message == ProfileMessageId.ConnectionFailure ? "Sorry, we couldn't make that happen."
                : message == ProfileMessageId.DenySuccess ? "You have successfully denied being connected to " + profileUser.UserName + "."
                : message == ProfileMessageId.SentMessage ? "Your message has been sent to " + profileUser.UserName + "."
                : "";

            return View(profileUser);
        }

        // GET: Profile/SeeMoreImages
        public ActionResult SeeMoreImages(string username)
        {
            User profileUser = manager.FindById(User.Identity.GetUserId());

            if (username != null) //Traveling to another user's profile
            {
                profileUser = db.Users.Where(user => user.UserName == username).First();
            }
            else //Traveling to personal profile page
            {
               
            }

            //add user's location images
            List<LocationImage> images = db.LocationImages.Where(i => i.User.Id == profileUser.Id).ToList();
            profileUser.UserLocationImages = images;

            return View(profileUser);
        }

        // GET: Profile/SeeMoreVideos
        public ActionResult SeeMoreVideos(string username)
        {
            User profileUser = manager.FindById(User.Identity.GetUserId());

            if (username != null) //Traveling to another user's profile
            {
                profileUser = db.Users.Where(user => user.UserName == username).First();
            }
            else //Traveling to personal profile page
            {

            }

            //add user's location images
            List<Video> videos = db.Videos.Where(i => i.User.Id == profileUser.Id).ToList();
            ViewBag.VideosCount = videos.Count();
            profileUser.UserLocationVideos = videos;

            return View(profileUser);
        }
        

        // GET: Connections
        [Authorize]

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Events/Create.cshtml
@model TentsNTrails.Models.Events
@{
    ViewBag.Title = "Create";
}

<h2>Create Event</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <!--LOCATION-->
        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LocationID, (SelectList)ViewBag.LocationID, "Select a Location...", htmlAttributes: new { id = "location-select", @class = "form-control", onchange = "setSelectListTextColor('location-select');" })
                <script src="~/Scripts/set-select-list-text-color.js"></script>
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <!--NAME-->
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--DESCRIPTION-->
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, 10, 55, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--DATE-->
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>


        <!-- BUTTONS -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">

                <!-- CREATE -->
                <input type="submit" value="Create" class="btn btn-default" />

                <!-- CANCEL -->
                <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Index", "Events")'">Cancel</button>

            </div>
        </div>

    </div>
}

<p>
    @Html.ActionLink("Back to List", "Index", "Events", null, null)
</p>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Events/Delete.cshtml
@model TentsNTrails.Models.Events

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Event</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location.Label)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.Label)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Events/Edit.cshtml
@model TentsNTrails.Models.Events

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Event</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EventID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, "LocationID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Events/Index.cshtml
@model IEnumerable<TentsNTrails.Models.Events>
@using TentsNTrails.Models
@using Microsoft.AspNet.Identity

 <!-- Google Maps Scripting -->
<script src="http://maps.googleapis.com/maps/api/js"></script>
<script src="~/Scripts/google-map-setup.js"></script>
<script>
    var addMarkers = function(map, markers) {
        @foreach (var item in Model) {
            @:console.log("latitude:" + @item.Location.Latitude + " longitude: " +  @item.Location.Longitude);
            @:var marker = new google.maps.Marker({position: new google.maps.LatLng(@item.Location.Latitude, @item.Location.Longitude), map: map});
            @:var infowindow = new google.maps.InfoWindow({content: 'Loading...'});
            @:marker.html='<div class="label"><a>@item.Name</a></div>';
            @:google.maps.event.addListener(marker, 'click', function() {infowindow.setContent(this.html); infowindow.open(map,this);});
            @:markers.push(marker);
       }
    };
    var centerLat = @ViewBag.centerLatitude;
    var centerLng = @ViewBag.centerLongitude;
    var minZoom = 9;
    var ourMap = new TntMap(centerLat,centerLng, addMarkers, minZoom);
    ourMap.create();
</script>

@{
    ViewBag.Title = "Index";
}

<h2>Events <a href="/Events/Create"><span style="color: green;"><i class="glyphicon glyphicon-plus"></i></span></a></h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<p style="color: green;">
    @ViewBag.SuccessMessage
</p>

<!-- MAP -->
<div class="row" style="padding-top:15px;">
    <div class="col-xs-12">
        <div id="googleMap" style="width:100%;height:300px;"></div>
        <p></p>
    </div>
</div>

@**<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            Organizer
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "Details", new { id = item.EventID })
        </td>
        <td>
            @Html.ActionLink(item.Location.Label, "Details", "Location", new { id = item.LocationID }, null)
        </td>
        <td>
            @Html.DisplayFor(e => item.Date)
        </td>
        <td>
            @Html.ActionLink(item.Organizer.UserName, "Index", "Profile", new { Username = item.Organizer.UserName }, null)
        </td>
        @if (User.IsInRole("Admin") || User.Identity.IsAuthenticated && User.Identity.GetUserName().Equals(item.Organizer.UserName))
        {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.EventID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.EventID })
            </td>
        }
    </tr>
}

</table>**@


<!-- LOCATIONS -->
@{
    int padding = 7;
    int count = Model.Count();
    for (int i = 0; i < count; i += 2)
    {
        <div class="row" style="padding: 0px @(padding)px 0px @(padding)px">
            @for (int j = i; j < Math.Min(i + 2, count); j++)
            {
                Events item = Model.ToList()[j];
                <div class="col-xs-12 col-md-6" style="padding: @(padding)px;">
                    <div id="review" style="min-height: 124px; min-width:370px">
                        @{ Html.RenderAction("Summary", "Events", new { id = item.EventID, redirectAction = "Index", redirectController = "Events" }); }
                    </div>
                </div>
            }
        </div>
    }
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Events/Summary.cshtml
@model TentsNTrails.Models.Events

<!--DETAILS-->
<div style="min-height:@(ViewBag.size)">
    <span style="font-size: 16px;"><b>@Html.ActionLink(Model.Name, "Details", "Events", new { id = Model.EventID }, new { title = "View Details" })&nbsp;&nbsp;&nbsp;(@Model.Date.Month/@Model.Date.Day)</b></span>
    <br />
    @Html.ActionLink(Model.Location.Label, "Details", "Location", new { id = Model.LocationID }, new { title = "View Location" })
    <br />
    Organizer: @Model.Organizer.UserName
    <br />
    @Model.Participants.Count
    @if (Model.Participants.Count > 1 || Model.Participants.Count == 0)
    {
        @Html.Raw("people are going");
    }
    else
    {
        @Html.Raw("person is going");
    }
    @if (User.IsInRole("Admin"))
    {
        <span style="float:right">
            <button class="btn btn-default" title="Edit" onclick="location.href='@Url.Action("Edit", new { id = Model.EventID})'">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </button>
            <button class="btn btn-default" title="Delete" onclick="location.href='@Url.Action("Delete", new { id = Model.EventID})'">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            </button>
        </span>
    }
</div>