CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Controllers/LocationFlagController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using TentsNTrails.Models;

namespace TentsNTrails.Controllers
{
    public class LocationFlagController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<User> manager;
            
        public LocationFlagController () 
        {
            manager = new UserManager<User>(new UserStore<User>(db));
        }

        // GET: LocationFlag
        [Authorize]
        public ActionResult Index()
        {
            User currentUser = manager.FindById(User.Identity.GetUserId());
            
            var locationFlags = db.LocationFlags.Include(l => l.Location).
                Where(l => l.User.Id == currentUser.Id).ToList();

            LocationFlagViewModel viewModel = new LocationFlagViewModel();

            if (locationFlags.Count() == 0)
            {
                // they haven't saved any locations
                viewModel.HasSavedLocations = false;
                viewModel.BeenThereLocations = new List<LocationFlag>();
                viewModel.WantToGoLocations = new List<LocationFlag>();
                viewModel.GoAgainLocations = new List<LocationFlag>();
            }
            else
            {
                // Fill the three lists with their respective LocationFlags
                viewModel.BeenThereLocations = locationFlags.Where(l => l.Flag == Flag.HaveBeen).ToList();
                viewModel.WantToGoLocations = locationFlags.Where(l => l.Flag == Flag.WantToGo).ToList();
                viewModel.GoAgainLocations = locationFlags.Where(l => l.Flag == Flag.GoAgain).ToList();
                viewModel.HasSavedLocations = true;
                ViewBag.centerLatitude = 39.8282;
                ViewBag.centerLongitude = -98.5795;
            }

            return View(viewModel);
        }

        // GET: LocationFlag/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label");
            return View();
        }

        // POST: LocationFlag/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "FlagID,LocationID,Flag")] LocationFlag locationFlag)
        {
            if (ModelState.IsValid)
            {
                db.LocationFlags.Add(locationFlag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label", locationFlag.LocationID);
            return View(locationFlag);
        }

        // GET: LocationFlag/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LocationFlag locationFlag = db.LocationFlags.Find(id);
            if (locationFlag == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label", locationFlag.LocationID);
            return View(locationFlag);
        }

        // POST: LocationFlag/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "FlagID,LocationID,Flag")] LocationFlag locationFlag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(locationFlag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "Label", locationFlag.LocationID);
            return View(locationFlag);
        }

        // GET: LocationFlag/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LocationFlag locationFlag = db.LocationFlags.Find(id);
            if (locationFlag == null)
            {
                return HttpNotFound();
            }
            return View(locationFlag);
        }

        // POST: LocationFlag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            LocationFlag locationFlag = db.LocationFlags.Find(id);
            db.LocationFlags.Remove(locationFlag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TentsNTrails.Models;
using PagedList;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity.EntityFramework;

namespace TentsNTrails.Controllers
{
    public class UsersController : Controller
    {

        private UserManager<User> manager;

        public UsersController()
        {
        }

        public UsersController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var users = from s in db.Users select s;
            

            int pageSize = 8;
            int pageNumber = (page ?? 1);

            if (searchString ==  "" || searchString == null)
            {
                // Basically return 0 results
                users = users.Where(q => q.PhoneNumber == "9999999999");

                ViewBag.rowCount = users.Count().ToString();

                return View(users.ToPagedList(pageNumber, pageSize));
            }
            else if (!String.IsNullOrEmpty(searchString))
            {
                // Find the users that contain the search string 
                users = users.Where(u => u.UserName.ToLower().Contains(searchString)
                                        || (u.LastName.ToLower().Contains(searchString) && u.Private == false)
                                        || u.FirstName.ToLower().Contains(searchString) && u.Private == false);
            }


            // For each dictionary, the username is the key and the boolean is the value
            ViewBag.IsConnectedDictionary = new Dictionary<string, bool>();
            ViewBag.HasConnectionRequestDictionary = new Dictionary<string, bool>();
            ViewBag.HasSentRequestDictionary = new Dictionary<string, bool>();

            if (User.Identity.IsAuthenticated)
            {
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                ViewBag.currentUser = currentUser.UserName;

                // Remove current user from the list if they're there.
                users = users.Where(u => u.UserName != currentUser.UserName);
                List<User> userList = users.ToList();

                // Check if the two users are already connected some way
                foreach (var user in userList)
                {
                    // Check for connection
                    var connection = db.Connections.Where(c => (c.User1.UserName == currentUser.UserName && c.User2.UserName == user.UserName) ||
                        (c.User2.UserName == currentUser.UserName && c.User1.UserName == user.UserName));
                    if (connection.Count() > 0)
                    {
                        ViewBag.IsConnectedDictionary.Add(user.UserName, true);
                    }
                    else
                    {
                        ViewBag.IsConnectedDictionary.Add(user.UserName, false);
                    }

                    // Check if the person whose profile we're looking at has sent a ConnectionRequest
                    var requestTo = db.ConnectionRequests.Where(c => (c.RequestedUser.UserName == currentUser.UserName && c.Sender.UserName == user.UserName));
                    if (requestTo.Count() > 0)
                    {
                        ViewBag.HasConnectionRequestDictionary.Add(user.UserName, true);
                        ViewBag.HasSentRequestDictionary.Add(user.UserName, false);
                    }
                    else
                    {
                        var requestFrom = db.ConnectionRequests.Where(c => (c.Sender.UserName == currentUser.UserName && c.RequestedUser.UserName == user.UserName));
                        if (requestFrom.Count() > 0)
                        {
                            ViewBag.HasConnectionRequestDictionary.Add(user.UserName, false);
                            ViewBag.HasSentRequestDictionary.Add(user.UserName, true);
                        }
                        else
                        {
                            ViewBag.HasConnectionRequestDictionary.Add(user.UserName, false);
                            ViewBag.HasSentRequestDictionary.Add(user.UserName, false);
                        }
                    }
                }
            }

            users = users.OrderByDescending( u => u.EnrollmentDate);
            ViewBag.rowCount = users.Count().ToString();


            return View(users.ToPagedList(pageNumber, pageSize));
        }

        // GET: Users
        // Admin Control
        [Authorize(Roles = "Admin")]
        public ActionResult AdminControl(string currentFilter, string searchString, int? page)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var users = from s in db.Users select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(u => u.UserName.ToLower().Contains(searchString)
                                       || u.LastName.ToLower().Contains(searchString)
                                       || u.FirstName.ToLower().Contains(searchString));
            }

            users = users.OrderByDescending(u => u.EnrollmentDate);

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(users.ToPagedList(pageNumber, pageSize));
        }

        // GET: Users/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,EnrollmentDate,FirstName,LastName,Private,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,EnrollmentDate,FirstName,LastName,Private,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Ban/5
        [Authorize(Roles = "Admin")]
        public ActionResult Ban(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Ban/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Shared/Join.cshtml
@model TentsNTrails.Models.JoinLocationsViewModel
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Join";
    int padding = 10;
}

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-xs-12">
            <div class="col-xs-9">
                <h2>Join Locations</h2>
                <p style="color: red;">@ViewBag.ErrorMessage</p>
                <p>
                    The reviews and media items from <text class="no-wrap bold">Location A</text> 
                    will be added into <text class="no-wrap bold">Location B</text>, 
                    and <text class="no-wrap bold">Location A</text> will be removed.
                </p>
            </div>
            <div class="col-xs-3">
                <br />

                <!--INPUT MERGE BUTTON-->
                <input class="btn btn-default" type="submit" value="Accept Merge" style="float:right" />

            </div>

        </div>
    </div>

    <div class="row" style="padding:0px @(padding)px">

        <div class="col-xs-12 col-sm-6" style="padding:@(padding)px">
            <div id="review">
                <h3>Location A</h3>
                <h6>The location to be removed.</h6>

                <!--INPUT SEARCH A-->
                <div class="input-group">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                    @Html.TextBox("SearchStringA", null, new { @class="form-control", placeholder = "Search by Name"})
                                        @*
        <input type="text" class="form-control" name="SearchStringA" id="SearchStringA">
                                        *@
                </div>

                <table class="table">
                    @*
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Latitude</th>
                            <th>Longitude</th>
                        </tr>
                    *@
                    @foreach (var item in Model.LocationA)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="LocationA" value="@item.LocationID">
                            </td>
                            <td>
                                @{ Html.RenderAction("JoinSummary", "Location", new { id = item.LocationID }); }
                            </td>
                        </tr>
                    }

                </table>
                Page @(Model.LocationA.PageCount < Model.LocationA.PageNumber ? 0 : Model.LocationA.PageNumber) of @Model.LocationA.PageCount

                @Html.PagedListPager(Model.LocationA, pageA => Url.Action("Join", new { pageA, pageB = Model.LocationB.PageNumber }))
            </div>
        </div>
        <div class="col-xs-12 col-sm-6" style="padding:@(padding)px">
            <div id="review">

                <h3>Location B</h3>
                <h6>The location to be kept.</h6>

                <!--INPUT SEARCH B-->
                <div class="input-group">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                    @Html.TextBox("SearchStringB", null, new { @class="form-control", placeholder = "Search by Name"})
                    @*
    <input type="text" class="form-control" name="SearchStringB" id="SearchStringB">
                    *@
                </div>

                <table class="table">
                    @*
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Latitude</th>
                            <th>Longitude</th>
                        </tr>
                    *@

                    @foreach (var item in Model.LocationB)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="LocationB" value="@item.LocationID">
                            </td>
                            <td>
                                @{ Html.RenderAction("JoinSummary", "Location", new { id = item.LocationID }); }
                            </td>
                        </tr>
                    }

                </table>
                Page @(Model.LocationB.PageCount < Model.LocationB.PageNumber ? 0 : Model.LocationB.PageNumber) of @Model.LocationB.PageCount

                @Html.PagedListPager(Model.LocationB, pageB => Url.Action("Join", new { pageA = Model.LocationA.PageNumber, pageB }))
            </div>
        </div>
    </div>
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Shared/_FooterBody.cshtml
<!--FOOTER-->
<hr />
<footer style="float: right">
    <p>
        <a href="@Url.Action("About", "Home")" title="About">
            &nbsp;&copy; @DateTime.Now.Year - tents n trails&nbsp;
        </a>
    </p>
</footer>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Shared/_FooterFixedBottom.cshtml
@*
    <!--FOOTER-->
    <div class="navbar navbar-fixed-bottom">
        <div class="container">
            <div class="navbar-header" style="float: right">
                @Html.ActionLink("About", "About", "Home", null, new { @style = "color:#999;" })
                &nbsp;&nbsp;
                &copy; @DateTime.Now.Year - tents n trails
            </div>
        </div>
    </div>
*@

<div class="custom-footer">
    <div style="float: right">
        <a href="@Url.Action("About", "Home")" title="About">
            &nbsp;&copy; @DateTime.Now.Year - tents n trails&nbsp;
        </a>
    </div>
</div>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="main">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - tents n trails</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- NAVBAR -->
    @Html.Partial("_Navbar")

    <!-- CONTENT -->
    <div class="container body-content non-home">
        @RenderBody()
        @Html.Partial("_FooterBody")
    </div>

    <!--SCRIPTS-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquerythumb")
    @RenderSection("scripts", required: false)
</body>
</html>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html class="home">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - tents n trails</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- NAVBAR -->
    @Html.Partial("_Navbar")

    <!-- CONTENT -->
    <div class="container body-content home" style="padding:15px">
        @RenderBody()
    </div>
    @Html.Partial("_FooterFixedBottom")

    <!--SCRIPTS-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Shared/_Navbar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">

        <!-- COLLAPSABLE BUTTON -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href="@Url.Action("Index", "Home")" class="navbar-brand" title="Home">
                <span class="hidden-xs"  style="color:#d5d5d5; display:inline"                >tents<span style="color:#9acb6a; display:inline">n</span>trails</span>
                <span class="visible-xs" style="color:#d5d5d5; display:inline;padding-top:5px">tents<span style="color:#9ecb6a; display:inline">n</span>trails</span>
            </a>
     </div>
        
        <!-- LINKS -->
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Locations", "Index", "Location")</li>
                @Html.Partial("_SocialMenuPartial")
            </ul>
            @Html.Partial("_LoginPartial")
        </div>

    </div>
</div>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Shared/_SocialMenuPartial.cshtml
<!-- SOCIAL -->
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Social
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu" id="noUnderline">
        <li>@Html.ActionLink("Find Friends", "Index", "Users")</li>
        <li>@Html.ActionLink("Events", "Index", "Events")</li>
        <li>@Html.ActionLink("Leaderboard", "Index", "Leaderboard")</li> 
    </ul>
</li>

@*
<!-- SOCIAL -->
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Social
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu" id="noUnderline">
        <li><a href="@Url.Action("Index", "Users")"><span class="glyphicon glyphicon-search"></span>&nbsp;Find Friends</a></li>
        <li><a href="@Url.Action("Index", "Events")"><span class="glyphicon glyphicon-calendar"></span>&nbsp;Events</a></li>
        <li><a href="@Url.Action("Index", "Leaderboard")"><span class="glyphicon glyphicon-th-list"></span>&nbsp;Leaderboard</a></li>
        <li class="divider"></li>
        <li><a href="@Url.Action("Index", "Users")">Find Friends&nbsp;<span class="glyphicon glyphicon-search" style="float:right"></span></a></li>
        <li><a href="@Url.Action("Index", "Events")">Events&nbsp;<span class="glyphicon glyphicon-calendar" style="float:right"></span></a></li>
        <li><a href="@Url.Action("Index", "Leaderboard")">Leaderboard&nbsp;<span class="glyphicon glyphicon-th-list" style="float:right"></span></a></li>
    </ul>
</li>
*@

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Shared/_UserMenuPartial.cshtml
@using Microsoft.AspNet.Identity
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        @Html.Raw("Hello " + User.Identity.GetUserName() + "!")
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu" id="noUnderline">
        <li>
            <a href="@Url.Action("Index", "Message")" title="My Messages">
                Messages&nbsp;@{Html.RenderAction("UnreadCount", "Message");}
            </a>
        </li>
        <li>@Html.ActionLink("Reviews", "Index", "Review")</li>
        <li>@Html.ActionLink("Bookmarked Locations", "Index", "LocationFlag")</li>
        <li>@Html.ActionLink("Connections", "Connections", "Profile")</li>
        @*<li><a href="@Url.Action("Index", "Profile")"><span class="glyphicon glyphicon-user"></span> My Profile</a></li>*@
        <li>@Html.ActionLink("Profile", "Index", "Profile")</li>
        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
        {
            <li class="divider"></li>
            <li>@Html.ActionLink("User Management", "AdminControl", "Users")</li>
            <li>@Html.ActionLink("Join Locations", "Join", "Location")</li>
        }
    </ul>
</li>