CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Models/Locations/LocationFeature.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TentsNTrails.Models
{
    /// <summary>
    /// This is a pure bridge entity between a Location and a NaturalFeature.
    /// </summary>
    public class LocationFeature
    {
        /// <summary>
        /// Index of the associated Location.
        /// </summary>
        [Key,  ForeignKey("Location"), Column(Order = 0)]
        public int LocationID { get; set; }

        /// <summary>
        /// Index of the associated NaturalFeature.
        /// </summary>
        [Key, ForeignKey("NaturalFeature"), Column(Order = 1)]
        public int NaturalFeatureID { get; set; }

        /// <summary>
        /// The Location referenced by this LocationFeature.
        /// </summary>
        public virtual Location Location { get; set; }

        /// <summary>
        /// The NaturalFeature referenced by this LocationFeature.
        /// </summary>
        public virtual NaturalFeature NaturalFeature { get; set; }



        /// <summary>
        /// Create a new LocationFeature with uninitialized fields.
        /// </summary>
        public LocationFeature() { }

        /// <summary>
        /// Create a new LocationFeature.
        /// </summary>
        /// <param name="locationID">The index of the Location to associate.</param>
        /// <param name="naturalFeatureID">The index of the NaturalFeature to associate.</param>
        public LocationFeature(int locationID, int naturalFeatureID)
        {
            this.LocationID = locationID;
            this.NaturalFeatureID = naturalFeatureID;
        }
    }
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Models/Locations/LocationFlag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TentsNTrails.Models
{
    public enum  Flag {
        [Display(Name = "Have Been")]
        HaveBeen,
        [Display(Name = "Want to Go")]
        WantToGo,
        [Display(Name = "Want to Go Again")]
        GoAgain
    }

    public class LocationFlag
    {
        [Key]
        public int FlagID { get; set; }
        //public int UserID { get; set; }
        public int LocationID { get; set; }
        public Flag Flag { get; set; }

        public virtual User User { get; set; }
        public virtual Location Location { get; set; }
    }
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Models/Locations/ReviewIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TentsNTrails.Models
{
    public class ReviewIndexViewModel
    {
        public Review Review { get; set; }
        public Image PreviewImage { get; set; }
    }
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Controllers/RecreationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TentsNTrails.Models;

namespace TentsNTrails.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RecreationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Recreation
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.Recreations.ToList());
        }

        // GET: Recreation/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recreation recreation = db.Recreations.Find(id);
            if (recreation == null)
            {
                return HttpNotFound();
            }
            return View(recreation);
        }

        // GET: Recreation/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // **************************************
        // EDITED (Non-Standard Scaffolded Code)
        // **************************************
        // POST: Recreation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "RecreationID,Label")] Recreation recreation)
        {
            if (ModelState.IsValid)
            {
                // initialize DateTime Stamps
                recreation.DateCreated = DateTime.UtcNow;
                recreation.DateModified = recreation.DateCreated;

                // save changes
                db.Recreations.Add(recreation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(recreation);
        }

        // GET: Recreation/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recreation recreation = db.Recreations.Find(id);
            if (recreation == null)
            {
                return HttpNotFound();
            }
            return View(recreation);
        }

        // **************************************
        // EDITED (Non-Standard Scaffolded Code)
        // **************************************
        // POST: Recreation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "RecreationID,Label,DateCreated")] Recreation recreation)
        {
            if (ModelState.IsValid)
            {
                // update DateModified
                recreation.DateModified = DateTime.UtcNow;

                // save changes
                db.Entry(recreation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(recreation);
        }

        // GET: Recreation/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recreation recreation = db.Recreations.Find(id);
            if (recreation == null)
            {
                return HttpNotFound();
            }
            return View(recreation);
        }

        // POST: Recreation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Recreation recreation = db.Recreations.Find(id);
            db.Recreations.Remove(recreation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TentsNTrails.Models;
using PagedList;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity.EntityFramework;

namespace TentsNTrails.Controllers
{
    public class UsersController : Controller
    {

        private UserManager<User> manager;

        public UsersController()
        {
        }

        public UsersController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var users = from s in db.Users select s;
            

            int pageSize = 8;
            int pageNumber = (page ?? 1);

            if (searchString ==  "" || searchString == null)
            {
                // Basically return 0 results
                users = users.Where(q => q.PhoneNumber == "9999999999");

                ViewBag.rowCount = users.Count().ToString();

                return View(users.ToPagedList(pageNumber, pageSize));
            }
            else if (!String.IsNullOrEmpty(searchString))
            {
                // Find the users that contain the search string 
                users = users.Where(u => u.UserName.ToLower().Contains(searchString)
                                        || (u.LastName.ToLower().Contains(searchString) && u.Private == false)
                                        || u.FirstName.ToLower().Contains(searchString) && u.Private == false);
            }


            // For each dictionary, the username is the key and the boolean is the value
            ViewBag.IsConnectedDictionary = new Dictionary<string, bool>();
            ViewBag.HasConnectionRequestDictionary = new Dictionary<string, bool>();
            ViewBag.HasSentRequestDictionary = new Dictionary<string, bool>();

            if (User.Identity.IsAuthenticated)
            {
                User currentUser = UserManager.FindById(User.Identity.GetUserId());
                ViewBag.currentUser = currentUser.UserName;

                // Remove current user from the list if they're there.
                users = users.Where(u => u.UserName != currentUser.UserName);
                List<User> userList = users.ToList();

                // Check if the two users are already connected some way
                foreach (var user in userList)
                {
                    // Check for connection
                    var connection = db.Connections.Where(c => (c.User1.UserName == currentUser.UserName && c.User2.UserName == user.UserName) ||
                        (c.User2.UserName == currentUser.UserName && c.User1.UserName == user.UserName));
                    if (connection.Count() > 0)
                    {
                        ViewBag.IsConnectedDictionary.Add(user.UserName, true);
                    }
                    else
                    {
                        ViewBag.IsConnectedDictionary.Add(user.UserName, false);
                    }

                    // Check if the person whose profile we're looking at has sent a ConnectionRequest
                    var requestTo = db.ConnectionRequests.Where(c => (c.RequestedUser.UserName == currentUser.UserName && c.Sender.UserName == user.UserName));
                    if (requestTo.Count() > 0)
                    {
                        ViewBag.HasConnectionRequestDictionary.Add(user.UserName, true);
                        ViewBag.HasSentRequestDictionary.Add(user.UserName, false);
                    }
                    else
                    {
                        var requestFrom = db.ConnectionRequests.Where(c => (c.Sender.UserName == currentUser.UserName && c.RequestedUser.UserName == user.UserName));
                        if (requestFrom.Count() > 0)
                        {
                            ViewBag.HasConnectionRequestDictionary.Add(user.UserName, false);
                            ViewBag.HasSentRequestDictionary.Add(user.UserName, true);
                        }
                        else
                        {
                            ViewBag.HasConnectionRequestDictionary.Add(user.UserName, false);
                            ViewBag.HasSentRequestDictionary.Add(user.UserName, false);
                        }
                    }
                }
            }

            users = users.OrderByDescending( u => u.EnrollmentDate);
            ViewBag.rowCount = users.Count().ToString();


            return View(users.ToPagedList(pageNumber, pageSize));
        }

        // GET: Users
        // Admin Control
        [Authorize(Roles = "Admin")]
        public ActionResult AdminControl(string currentFilter, string searchString, int? page)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var users = from s in db.Users select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(u => u.UserName.ToLower().Contains(searchString)
                                       || u.LastName.ToLower().Contains(searchString)
                                       || u.FirstName.ToLower().Contains(searchString));
            }

            users = users.OrderByDescending(u => u.EnrollmentDate);

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(users.ToPagedList(pageNumber, pageSize));
        }

        // GET: Users/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,EnrollmentDate,FirstName,LastName,Private,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,EnrollmentDate,FirstName,LastName,Private,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Ban/5
        [Authorize(Roles = "Admin")]
        public ActionResult Ban(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Ban/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Location/Browse.cshtml
@model TentsNTrails.Models.BrowseLocationsViewModel
@using TentsNTrails.Models
@using PagedList.Mvc

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Browse Locations";
}

<div class="row">

    <!--TITLE-->
    <div class="col-xs-12 col-sm-6">
        <h2>@ViewBag.Title <a href="/Location/Create" title="Create a new Location"><span title="Add New Location" style="color: green;"><i class="glyphicon glyphicon-plus"></i></span></a></h2>
    </div>

</div>

@{Html.RenderAction("GoogleMap", "Location", new { height = 300, width = 0, minZoom = 9, center = Location.CENTER, locations = Model.Locations.ToList() });}
<br />

<!-- SEARCH -->
@using (Html.BeginForm())
{
    @*<div style="float:left">
        @Html.DropDownListFor(m => m.recreationID, Model.Recreations, "Recreation Type")
    </div>*@
    <div>
        @Html.DropDownListFor(m => m.recreationID, Model.Recreations, htmlAttributes: new { @class = "btn dropdown"})
        @Html.TextBoxFor(m => m.query, null, htmlAttributes: new { @class = "btn", style = "width:280px", type = "text", placeholder = "Search by Name or State" })
        <button id="btn" class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
        @if (ViewBag.Recreation != null)
        {
            <span style="margin:12px"></span>
            <span class="tag tag-recreation tag-normal-size">
                @ViewBag.Recreation
            </span>
        }
        @if (ViewBag.SearchString != null && ViewBag.SearchString != "")
        {
            <span style="padding:12px">Showing results for <b>"@ViewBag.SearchString"</b></span>
        }
    </div>
}<br />

<!-- LOCATIONS -->
@{
    int padding = 7;
    int count = Model.Locations.Count();
    for (int i = 0; i < count; i += 2)
    {
        <div class="row" style="padding: 0px @(padding)px 0px @(padding)px">
            @for (int j = i; j < Math.Min(i + 2, count); j++)
            {
                Location item = Model.Locations[j];
                <div class="col-xs-12 col-md-6" style="padding: @(padding)px;">
                    <div id="review" style="min-height: 124px">
                        @{ Html.RenderAction("Summary", "Location", new { id = item.LocationID, redirectAction = "Browse", redirectController = "Location" }); }
                    </div>
                </div>
            }
        </div>
    }
}

<br />

<!--PAGING-->
Page @(Model.Locations.PageCount < Model.Locations.PageNumber ? 0 : Model.Locations.PageNumber) of @Model.Locations.PageCount
@Html.PagedListPager(Model.Locations, page => Url.Action("Browse", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

@if (Request.IsAuthenticated && User.IsInRole("Admin"))
{
    @Html.ActionLink("Recreations", "Index", "Recreation")
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Location/Delete.cshtml
@model TentsNTrails.Models.Location

@{
    ViewBag.Title = "Delete";
}

<h2>@Model.Label</h2>

<h4>Are you sure you want to delete this Location?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.State.Name)</dt>
        <dd>@Html.DisplayFor(model => model.State.Name)</dd>

        <dt>@Html.DisplayNameFor(model => model.Latitude)</dt>
        <dd>@Html.DisplayFor(model => model.Latitude)</dd>

        <dt>@Html.DisplayNameFor(model => model.Longitude)</dt>
        <dd>@Html.DisplayFor(    model => model.Longitude)</dd>

        <dt>@Html.DisplayNameFor(model => model.DateCreated)</dt>
        <dd>@Html.DisplayFor(    model => model.DateCreated)</dd>

        <dt>@Html.DisplayNameFor(model => model.DateModified)</dt>
        <dd>@Html.DisplayFor(    model => model.DateModified)</dd>

        <dt>@Html.DisplayNameFor(model => model.Description)</dt>
        <dd>@Html.DisplayFor(    model => model.Description)</dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            &nbsp;
            <button class="btn btn-default" onclick="location.href='@Url.Action("Browse")'">Cancel</button>
        </div>
    }
</div>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Location/GoogleMap.cshtml
@model TentsNTrails.Models.MapViewModel
@{
    string width  = Model.Width == 0 ? "100%" : Model.Width.ToString() + "px";
    string height = Model.Height.ToString() + "px"; 
}
<!-- Google Maps Scripting -->
<script src="http://maps.googleapis.com/maps/api/js"></script>
<script src="~/Scripts/google-map-setup.js"></script>
<script>
    var addMarkers = function(map, markers) {
        @foreach (var item in Model.Locations)
        {
            @:var marker = new google.maps.Marker({position: new google.maps.LatLng(@item.Latitude, @item.Longitude), map: map});
            @:var infowindow = new google.maps.InfoWindow({content: 'Loading...'});
            @:marker.html='<div><img id="location-image-preview" src="@Url.Content(item.PreviewImageURL)" title="Preview Image" alt="Image of @item.Label" style="width: 100px; height: auto; margin:0 auto;" /><br /><div class="label" text-align="center">@Html.ActionLink(item.Label, "Details", "Location", new { id = item.LocationID }, null)</div></div>';
            @:google.maps.event.addListener(marker, 'click', function() {infowindow.setContent(this.html); infowindow.open(map,this);});
            @:markers.push(marker);
        }
    };
    var ourMap = new TntMap(@Model.Center.Latitude, @Model.Center.Longitude, addMarkers, @Model.MinZoom);
    ourMap.create();
</script>
<!-- MAP -->
<div class="row" style="padding-top:15px;">
    <div class="col-xs-12">
        <div id="googleMap" style="width:@width; height:@height;"></div>
        <p></p>
    </div>
</div>

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Location/Index.cshtml
@model TentsNTrails.Models.LocationIndexViewModel
@using PagedList.Mvc
@using TentsNTrails.Models
@{
    int padding = 7;
    int minHeight = 124;
    int minWidth = 370;    
}

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Locations";
}
<div class="row">

    <!--TITLE-->
    <div class="col-xs-12 col-sm-6">
        <h2>Featured Locations <a href="/Location/Create" title="Create a new Location"><span title="Add New Location" style="color: green;"><i class="glyphicon glyphicon-plus"></i></span></a></h2>
    </div>

</div>

<br />

@{Html.RenderAction("GoogleMap", "Location", new { height = 300, width = 0, minZoom = 4, center = Location.CENTER, locations = Model.Locations });}

<div class="row">

    <!-- SEARCH -->
    <div class="col-xs-12 col-sm-6">

        <!-- SEARCH -->
        @using (Html.BeginForm("Browse", "Location"))
        {
            <div>
                @Html.DropDownList("recreationID", Model.Recreations, htmlAttributes: new { @class = "btn", id = "dropdownMenu1" })
                @Html.TextBox("query", null, htmlAttributes: new { @class = "btn", style = "width:280px", type = "text", placeholder = "Search by Name or State" })
                <button id="btn" class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
            </div>
        }
    </div>

    <!-- BROWSE ALL -->
    <div class="col-xs-12 col-sm-6">
        <button class="btn btn-default" onclick="location.href='@Url.Action("Browse")'" style="float:right">
            Browse All Locations
        </button>
    </div>
</div>

@if (User.Identity.IsAuthenticated)
{
    <!-- RECCOMENDATIONS -->
    <div class="row" style="padding: 0px @(padding)px 0px @(padding)px">
        <div class="col-xs-12">
            <hr />
            <h2>Your Recommendations</h2>
        </div>

        <!-- PERSONAL -->
        <div class="col-xs-12 col-md-6">

            <br />
            <h4>Based On Your Interests</h4>
            <div class="row">
                @if (Model.PersonalRecommendations.Count == 0)
                {
                    <div class="col-xs-12" style="padding: @(padding)px;">
                        <div id="review" style="min-height: @(minHeight)px">
                            <p>
                                <span style="color:red">We don't have any personal recommendations for you yet.</span>
                           </p>
                            <p>  
                                When you @Html.ActionLink("review", "Index", "Review")
                                or @Html.ActionLink("bookmark", "Index", "LocationFlag") locations, or list
                                what @Html.ActionLink("activities", "ChangeActivities", "Manage")
                                you enjoy, we will recommend locations based on what you like.
                            </p>
                        </div>
                    </div>

                }
                else
                {
                    foreach (var item in Model.PersonalRecommendations)
                    {
                        <div class="col-xs-12" style="padding: @(padding)px;">
                            <div id="review" style="min-height: @(minHeight)px">
                                @{ Html.RenderAction("Summary", "Location", new { id = item.LocationID }); }
                            </div>
                        </div>
                    }

                }
            </div>
        </div>

        <!-- FRIENDS -->
        <div class="col-xs-12 col-md-6">
            <br />
            <h4>Locations Your Friends Like</h4>
            <div class="row">
                @if (Model.FriendRecommendations.Count == 0)
                {
                    <div class="col-xs-12" style="padding: @(padding)px;">
                        <div id="review" style="min-height: @(minHeight)px">
                            <p>
                                <span style="color:red">We don't have any recommendations from your friends yet.</span>
                            </p>
                            <p>
                                When you @Html.ActionLink("connect", "Index", "Users") with other users,
                                we will recommend locations based on your friends' interests.
                            </p>
                        </div>
                    </div>

                }
                else
                {
                    foreach (var item in Model.FriendRecommendations)
                    {
                        <div class="col-xs-12" style="padding: @(padding)px;">
                            <div id="review" style="min-height: @(minHeight)px">
                                @{ Html.RenderAction("Summary", "Location", new { id = item.LocationID }); }
                            </div>
                        </div>
                    }
                }                
            </div>
        </div>


    </div>
}

<div class="row" style="padding: 0px @(padding)px 0px @(padding)px">
    <div class="col-xs-12">
        <hr />
    </div>

    <!-- TOP RATED LOCATION TABLE -->
    <div class="col-xs-12 col-md-6">
        <h2>Top Rated</h2>
        <div class="row">
            @foreach (var item in Model.TopRatedLocations)
            {
                <div class="col-xs-12" style="padding: @(padding)px;">
                    <div id="review" style="min-height: @(minHeight)px">
                        @{ Html.RenderAction("Summary", "Location", new { id = item.LocationID }); }
                    </div>
                </div>
            }
        </div>
    </div>

    <!-- RECENTLY ADDED LOCATION TABLE -->
    <div class="col-xs-12 col-md-6">
        <h2>Recently Added</h2>
        <div class="row">
            @foreach (var item in Model.MostRecentLocations)
            {
                <div class="col-xs-12" style="padding: @(padding)px;">
                    <div id="review" style="min-height: @(minHeight)px">
                        @{ Html.RenderAction("Summary", "Location", new { id = item.LocationID }); }
                    </div>
                </div>
            }
        </div>
    </div>

</div>

@if (Request.IsAuthenticated && User.IsInRole("Admin"))
{
    @Html.ActionLink("Recreations", "Index", "Recreation")
}

CS425-430/WebApplicationGroupProject/Tents n Trails/TentsNTrails/TentsNTrails/Views/Location/LocationThumbnail.cshtml
@model TentsNTrails.Models.Location

<div style="min-width:@(ViewBag.Size)px; max-width:@(ViewBag.Size)px; overflow: hidden">
    <img id="profile-picture"
         src="@Url.Content(Model.PreviewImageURL)"
         title="Profile Picture"
         alt="Image of @Model.Label"
         style="width: auto; height: @(ViewBag.Size)px; margin: 0 auto" />
</div>